%% x15_pio_figures.m
%  Reproduce Figures 7 and 8 of
%    R.K. Mehra & R.K. Prasanth, "Bifurcation and Limit Cycle Analysis of
%    Nonlinear Pilot Induced Oscillations", AIAA-98-4249.
%
%  Uses the existing X15_PIO.slx model, corresponding to the paper's
%  Figure-6 block diagram, and drives it. This script does not create,
%  rebuild, overwrite, or save the Simulink model:
%
%    theta_c --(+/-)--> [Kp] --> [e^{-s*tau}] --(+/-)--> [20] --> [sat +/-R]
%                 ^                                                    |
%                 |                                                  [1/s]
%                 |                                                    | delta
%                 |                        <---- delta feedback -------+
%                 |                                                    v
%                 +---------------- theta <------------ [ Airframe theta/delta ]
%
%    Airframe :  theta/delta = K_AF (s+0.029)(s+0.883)
%                             ---------------------------------------
%                             s^4 + 2.06 s^3 + 5.94 s^2 + 2.03 s + 0.053
%    Pilot    :  Kp * e^{-s*tau}          (paper p.150 / p.149)
%    Actuator :  delta_dot = sat_{+/-R}( 20*(u - delta) ),  R = 15 deg/s
%                (linear range -> 20/(s+20), exactly as the paper states)
%
%  FIGURE 7 is generated by sweeping Kp and measuring the amplitude of the
%  self-sustained (autonomous) oscillation: the model is given a short kick and
%  then runs free. The "jump" in Fig.7 is a HOPF BIFURCATION -- below the
%  critical gain the closed loop is stable and the oscillation decays to zero;
%  above it the loop is linearly unstable and the rate limiter bounds the
%  divergence into a large limit cycle. The critical gain is exactly the
%  classical gain margin of Kp*[20/(s+20)]*[theta/delta]*e^{-s*tau}.
%
%  FIGURE 8 is the same run at Kp = 5 plotted in the (theta, theta_dot) plane,
%  showing the trajectory spiralling out onto the stable limit cycle.
%
%  ---------------------------------------------------------------------------
%  READ THE NOTE ON AF_GAIN BELOW BEFORE COMPARING WITH THE PRINTED FIGURES.
%  ---------------------------------------------------------------------------

clear; clc; close all;

%% ------------------------- configuration -------------------------
% AF_GAIN: numerator gain of theta/delta.
%   86.9 -> exactly as printed in the paper. Gives a Hopf point at Kp = 0.304
%           (tau=0), i.e. PIO from Kp ~ 0.3, NOT 2.7 as the caption claims.
%   8.69 -> factor-of-10 reduction. Puts the tau=0 Hopf point at Kp = 3.04,
%           which matches the location of the tau=0 curve in the printed
%           Figure 7 (it rises at ~2.9-3.0). See the discussion notes.
AF_GAIN = 86.9;          % <-- set to 86.9 to use the paper's printed value

R       = 15;            % actuator slew-rate limit [deg/s]
K_ACT   = 20;            % actuator gain (linear range -> 20/(s+20))

tauList = [0 0.03 0.06 0.09];      % pilot effective delays [s]
KpList  = 0.05:0.05:5;             % pilot-gain grid for Figure 7

T_sim   = 90;            % [s] simulation length
T_kick  = 0.5;           % [s] duration of the initial command pulse
A_kick  = 1;             % amplitude of the initial command pulse [deg]
T_meas  = 30;            % [s] final window used to measure amplitude

Kp_fig8 = 5.0;           % pilot gain for Figure 8
tau_fig8= 0.0;           % delay for Figure 8

modelName = 'X15_PIO';

%% ------------------------- load the existing model -------------------------
% X15_PIO.slx must be in the same folder as this script or on the MATLAB path.
scriptFolder = fileparts(mfilename('fullpath'));
modelFile = fullfile(scriptFolder, [modelName '.slx']);

if ~isfile(modelFile)
    modelFile = which([modelName '.slx']);
end
if isempty(modelFile) || ~isfile(modelFile)
    error('x15_pio_figures:ModelNotFound', ...
        ['The existing model %s.slx could not be found. Place it in the ' ...
         'same folder as this script or add its folder to the MATLAB path.'], ...
        modelName);
end

if ~bdIsLoaded(modelName)
    load_system(modelFile);
end

% Configure logging in memory only. The .slx file is not modified or saved.
configureSignalLogging(modelName);

%% ------------------------- Figure 7 sweep -------------------------
nT = numel(tauList);  nK = numel(KpList);
amp = zeros(nT,nK);

in(1,nT*nK) = Simulink.SimulationInput(modelName);
q = 0;
for i = 1:nT
    for j = 1:nK
        q = q + 1;
        s = Simulink.SimulationInput(modelName);
        s = s.setVariable('Kp',    KpList(j));
        s = s.setVariable('thau',  max(tauList(i), 1e-9)); % Transport Delay needs >0
        s = s.setVariable('R',     R);
        s = s.setVariable('Akick', A_kick);
        s = s.setVariable('Tkick', T_kick);
        s = s.setBlockParameter([modelName '/Airframe'], ...
            'Numerator', sprintf('%.10g*conv([1 0.029],[1 0.883])', AF_GAIN));
        s = s.setModelParameter('StopTime', num2str(T_sim));
        s = s.setModelParameter('Solver','ode23t','RelTol','1e-6','MaxStep','0.01');
        in(q) = s;
    end
end

out = sim(in);          % use parsim(in) if you have Parallel Computing Toolbox

q = 0;
for i = 1:nT
    for j = 1:nK
        q = q + 1;
        [t,th,~] = getSig(out(q));
        seg = th(t >= T_sim - T_meas);
        amp(i,j) = 0.5*(max(seg) - min(seg));
    end
end

figure('Color','w','Position',[100 100 560 460]); hold on; box on; grid on;
sty = {'--','-.',':','-'};
for i = 1:nT
    plot(KpList, amp(i,:), sty{i}, 'Color','k', 'LineWidth',1.5);
end
xlabel('Pilot Gain'); ylabel('Limit Cycle Amplitude');
legend(compose('\\tau = %.2f', tauList), 'Location','northwest');
title(sprintf('X-15 limit cycle amplitude vs pilot gain (K_{AF} = %.4g)', AF_GAIN));
xlim([0 5]);

%% ------------------------- Figure 8 phase plane -------------------------
s8 = Simulink.SimulationInput(modelName);
s8 = s8.setVariable('Kp', Kp_fig8);
s8 = s8.setVariable('thau', max(tau_fig8,1e-9));
s8 = s8.setVariable('R', R);      
s8 = s8.setVariable('Akick', A_kick); s8 = s8.setVariable('Tkick', T_kick);
s8 = s8.setBlockParameter([modelName '/Airframe'], ...
    'Numerator', sprintf('%.10g*conv([1 0.029],[1 0.883])', AF_GAIN));
s8 = s8.setModelParameter('StopTime', num2str(T_sim));
s8 = s8.setModelParameter('Solver','ode23t','RelTol','1e-8','MaxStep','0.005');
o8 = sim(s8);
[~,th8,thd8] = getSig(o8);

figure('Color','w','Position',[700 100 520 500]);
plot(th8, thd8, 'k', 'LineWidth',0.4); grid on; box on;
xlabel('\theta'); ylabel('$\dot{\theta}$','Interpreter','latex');
title(sprintf('X-15 Limit Cycle at K_p = %.1f', Kp_fig8));
axis square;

%% ------------------------- report -------------------------
fprintf('\nHopf (PIO onset) gains -- classical gain margin of the loop:\n');
AF  = tf(AF_GAIN*conv([1 0.029],[1 0.883]), [1 2.06 5.94 2.03 0.053]);
act = tf(K_ACT,[1 K_ACT]);
for i = 1:nT
    sys = act*AF;  sys.InputDelay = tauList(i);
    [gm,~,wg,~] = margin(sys);
    fprintf('  tau = %.2f : Kp_crit = %6.3f   (w = %5.2f rad/s = %.2f Hz)\n', ...
             tauList(i), gm, wg, wg/2/pi);
end

%% ======================= helpers =======================
function [t,th,thd] = getSig(o)
    ls = o.logsout;
    th  = ls.get('theta').Values;
    thd = ls.get('theta_dot').Values;
    t = th.Time; th = th.Data; thd = thd.Data;
end

function configureSignalLogging(m)
% Configure the existing model to return theta and theta_dot in logsout.
    requiredBlocks = {'Airframe','Deriv'};
    for k = 1:numel(requiredBlocks)
        blockPath = [m '/' requiredBlocks{k}];
        if getSimulinkBlockHandle(blockPath) == -1
            error('x15_pio_figures:InvalidModel', ...
                'Required block "%s" was not found in %s.slx.', ...
                requiredBlocks{k}, m);
        end
    end

    set_param(m, 'SignalLogging','on', 'SignalLoggingName','logsout');

    ph = get_param([m '/Airframe'],'PortHandles');
    set_param(ph.Outport(1), 'Name','theta', 'DataLogging','on', ...
        'DataLoggingNameMode','Custom', 'DataLoggingName','theta');

    pd = get_param([m '/Deriv'],'PortHandles');
    set_param(pd.Outport(1), 'Name','theta_dot', 'DataLogging','on', ...
        'DataLoggingNameMode','Custom', 'DataLoggingName','theta_dot');
end
